version: '3.8'

services:
  db:
    image: postgres:13
    container_name: pluto_pizza_db
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: testPass
      POSTGRES_DB: pluto_pizza_db
    ports:
      - "5432:5432"
    volumes:
      - pluto_pizza_db_vol:/var/lib/postgresql/data

volumes:
  pluto_pizza_db_vol:
